name: Build 32-bit TA-Lib DLL
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022-buildtools -y
        choco install visualstudio2022-workload-vctools -y

    - name: Setup VS Environment
      shell: cmd  # 强制使用CMD执行此步骤
      run: |
        echo 调用VsDevCmd.bat设置环境变量
        call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=x86
        set

    - name: Configure CMake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A Win32 ..

    - name: Build TA-Lib
      shell: cmd
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: ta_lib.dll
        path: build/bin/Release/ta_lib.dll
