name: Build 32-bit TA-Lib DLL
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Patch CMakeLists.txt
      shell: cmd
      run: |
        powershell -Command "(Get-Content CMakeLists.txt) -replace 'status\(', 'message(STATUS ' | Set-Content CMakeLists.txt"

    - name: Install Dependencies
      shell: cmd
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022-buildtools -y
        choco install visualstudio2022-workload-vctools -y
        choco install nasm -y

    - name: Build Process
      shell: cmd
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.VCTools -property installationPath`) do set "VS_PATH=%%i"
        call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x86
        set Platform=x86

        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A Win32 -T "v143" ..

        @echo █ 关键修复：显式指定解决方案文件 █
        cmake --build . --config Release --target ta_lib --project TA-Lib.sln  # 添加--project参数

        copy bin\Release\ta_lib.dll ..\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ta_lib.dll
        path: ta_lib.dll
