name: Build TA-Lib 32-bit DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required tools
        run: |
          choco install -y msys2
          refreshenv
          C:\tools\msys64\usr\bin\pacman --noconfirm -Syuu
          C:\tools\msys64\usr\bin\pacman --noconfirm -S base-devel mingw-w64-i686-toolchain
        shell: powershell

      - name: Set up 32-bit MSYS2 environment
        run: |
          $env:PATH = "C:\tools\msys64\mingw32\bin;C:\tools\msys64\usr\bin;" + $env:PATH
        shell: powershell

      - name: Configure TA-Lib
        run: |
          cd src
          ./configure --host=i686-w64-mingw32 --enable-shared
        shell: msys2 {0}

      - name: Build TA-Lib
        run: |
          cd src
          make
        shell: msys2 {0}

      - name: Check build result
        run: |
          if (Test-Path src/.libs/*.dll) {
            Write-Host "Build succeeded, DLL files found."
          } else {
            Write-Error "Build failed, no DLL files found."
            exit 1
          }
        shell: powershell

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v3
        with:
          name: ta-lib-32bit-dll
          path: src/.libs/*.dll
