name: Build 32-bit TA-Lib DLL
on: 
  push:
    paths:
      - '**.cpp'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    env:
      CHOCO_LIB_DIR: C:\ProgramData\chocolatey\lib          # Chocolatey包安装目录
      VS_INSTALL_DIR: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools  # VS工具链目录

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # 缓存Chocolatey安装包
    - name: Cache Chocolatey
      uses: actions/cache@v3
      id: cache-choco
      with:
        path: ${{ env.CHOCO_LIB_DIR }}
        key: ${{ runner.os }}-choco-${{ hashFiles('**/CMakeLists.txt') }}-v1

    # 缓存Visual Studio编译工具
    - name: Cache Visual Studio
      uses: actions/cache@v3
      id: cache-vs
      with:
        path: ${{ env.VS_INSTALL_DIR }}
        key: ${{ runner.os }}-vs2022-${{ hashFiles('**/CMakeLists.txt') }}-v1

    # 仅当缓存未命中时安装依赖
    - name: Install Dependencies
      shell: cmd
      if: steps.cache-choco.outputs.cache-hit != 'true' || steps.cache-vs.outputs.cache-hit != 'true'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022-buildtools -y
        choco install visualstudio2022-workload-vctools -y
        choco install nasm -y

    # 编译流程（省略其他步骤）
    - name: Build Process
      shell: cmd
      run: |
        ...（同前序有效配置）
