name: Build 32-bit TA-Lib DLL
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies
      shell: cmd
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022-buildtools -y
        choco install visualstudio2022-workload-vctools -y
        choco install nasm -y

    - name: Build Process
      shell: cmd
      run: |
        @echo █ 动态定位VS编译环境 █
        for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Workload.VCTools -property installationPath`) do (
          set "VS_PATH=%%i"
        )
        if not defined VS_PATH (
          echo ❌ 未找到Visual Studio安装路径
          exit /b 1
        )

        @echo █ 激活编译环境 (路径: %VS_PATH%) █
        call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x86
        set | findstr "VCToolsInstallDir" || exit /b 1

        @echo █ 清理并重建编译目录 █
        rmdir /s/q build 2>nul
        mkdir build

        @echo █ 配置CMake工程 █
        cd build
        cmake -G "Visual Studio 17 2022" -A Win32 -T "v143" -D BUILD_SHARED_LIBS=ON ..

        @echo █ 编译核心目标 █
        cmake --build . --config Release --target ta_lib -- /m:8 || exit /b 1

        @echo █ 提取DLL文件 █
        copy bin\Release\ta_lib.dll ..\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ta_lib.dll
        path: ta_lib.dll
